"""add_uidx_name_roles

Revision ID: 166105baea23
Revises: c2088b4cab97
Create Date: 2023-04-25 12:16:13.822588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166105baea23'
down_revision = 'c2088b4cab97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'role', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    # ### end Alembic commands ###
