"""add user social

Revision ID: 321d1ffcbe3e
Revises: fdb61b922dd0
Create Date: 2023-05-14 13:16:25.458045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321d1ffcbe3e'
down_revision = 'fdb61b922dd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_social',
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('login', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_social')
    # ### end Alembic commands ###
