"""add foreign key user social

Revision ID: 4a589083212b
Revises: 321d1ffcbe3e
Create Date: 2023-05-14 13:19:57.751572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a589083212b'
down_revision = '321d1ffcbe3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_social', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_social', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_social', type_='foreignkey')
    op.drop_column('user_social', 'user_id')
    # ### end Alembic commands ###
