version: '3'
services:

  db-movie:
    container_name: db-movie
    build: db
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

  app-movie:
    container_name: app-movie
    build:
      context: app
      args:
        appuser: ${APP_USER}
    depends_on:
      - db-movie

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: es01
    depends_on:
      - db-movie
    expose:
      - "9200"

  etl:
    container_name: etl-movie
    build:
      context: etl
    depends_on:
      - es01

  fastapi:
    container_name: fastapi
    build:
      context: fastapi-solution
      args:
        appuser: ${APP_IO_USER}
    depends_on:
      - es01

  redis:
    image: redis
    container_name: redis
    hostname: redis
    command: redis-server
    expose:
      - "6379"
